"""
Knowledge base template module used by spawned agents.
This file exports a render function that returns a fully-formed Python
knowledge base module for a new domain agent.
"""

from typing import Dict

KNOWLEDGE_BASE_TEMPLATE = '''"""
Knowledge base for the {DOMAIN_CLASS_NAME} domain.
This module is generated by Universal AI and integrates with SharedKnowledgeBase.
"""

import os
import json
import re
from datetime import datetime
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv

from openai import OpenAI

try:
    from google import genai as google_genai
    GENAI_V2 = True
except ImportError:
    try:
        import google.generativeai as google_genai
        GENAI_V2 = False
    except ImportError:
        google_genai = None
        GENAI_V2 = False

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "").strip()
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-3.5-flash").strip()
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "").strip()
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "openrouter/auto").strip()
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "").strip()
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile").strip()
AI_PROVIDER_ORDER = [
    provider.strip().lower()
    for provider in os.getenv("AI_PROVIDER_ORDER", "gemini,openrouter,groq").split(",")
    if provider.strip()
]


class {DOMAIN_CLASS_NAME}KnowledgeBase:
    """
    Domain-specific knowledge base for {DOMAIN_CLASS_NAME}.
    Integrates with SharedKnowledgeBase and uses 3-Ws learning.
    """

    def __init__(self, memory_ai=None, storage_dir: str = "shared_knowledge"):
        self.memory_ai = memory_ai
        self.storage_dir = os.path.abspath(storage_dir)
        os.makedirs(self.storage_dir, exist_ok=True)
        self.custom_cache = os.path.join(self.storage_dir, "{DOMAIN_CLASS_NAME.lower()}_local.json")
        self.local_knowledge = self._load_local_knowledge()
        self.gemini_client = self._create_gemini_client()
        self.openrouter_client = self._create_openrouter_client()
        self.groq_client = self._create_groq_client()

    def _create_gemini_client(self):
        if not GEMINI_API_KEY or google_genai is None:
            return None
        if GENAI_V2:
            return google_genai.Client(api_key=GEMINI_API_KEY)
        google_genai.configure(api_key=GEMINI_API_KEY)
        return google_genai.GenerativeModel(GEMINI_MODEL)

    def _create_openrouter_client(self):
        if not OPENROUTER_API_KEY:
            return None
        headers = {"X-OpenRouter-Title": "Universal AI Ecosystem"}
        referer = os.getenv("OPENROUTER_HTTP_REFERER")
        if referer:
            headers["HTTP-Referer"] = referer
        return OpenAI(
            api_key=OPENROUTER_API_KEY,
            base_url="https://openrouter.ai/api/v1",
            default_headers=headers,
        )

    def _create_groq_client(self):
        if not GROQ_API_KEY:
            return None
        return OpenAI(api_key=GROQ_API_KEY, base_url="https://api.groq.com/openai/v1")

    def _load_local_knowledge(self) -> Dict[str, Any]:
        if not os.path.exists(self.custom_cache):
            return {"concepts": {}, "sources": []}
        try:
            with open(self.custom_cache, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return {"concepts": {}, "sources": []}

    def _save_local_knowledge(self) -> None:
        with open(self.custom_cache, "w", encoding="utf-8") as f:
            json.dump(self.local_knowledge, f, indent=2, ensure_ascii=False)

    def _clean_text(self, text: str) -> str:
        if not text:
            return ""
        text = text.strip()
        if "```" in text:
            start = text.index("```") + 3
            end = text.rfind("```")
            if end > start:
                text = text[start:end].strip()
        return text

    def _ask_ai(self, prompt: str) -> str:
        errors = []
        for provider in AI_PROVIDER_ORDER:
            try:
                if provider in {"gemini", "google", "google_ai_studio"}:
                    if not self.gemini_client:
                        raise EnvironmentError("GEMINI_API_KEY is not configured")
                    if GENAI_V2:
                        response = self.gemini_client.models.generate_content(
                            model=GEMINI_MODEL,
                            contents=prompt,
                            config={"temperature": 0.2, "max_output_tokens": 500},
                        )
                    else:
                        response = self.gemini_client.generate_content(
                            prompt,
                            generation_config={"temperature": 0.2, "max_output_tokens": 500},
                        )
                    return self._clean_text(getattr(response, "text", ""))

                if provider == "openrouter":
                    if not self.openrouter_client:
                        raise EnvironmentError("OPENROUTER_API_KEY is not configured")
                    response = self.openrouter_client.chat.completions.create(
                        model=OPENROUTER_MODEL,
                        messages=[{"role": "user", "content": prompt}],
                        temperature=0.2,
                        max_tokens=500,
                    )
                    return self._clean_text(response.choices[0].message.content)

                if provider == "groq":
                    if not self.groq_client:
                        raise EnvironmentError("GROQ_API_KEY is not configured")
                    response = self.groq_client.chat.completions.create(
                        model=GROQ_MODEL,
                        messages=[{"role": "user", "content": prompt}],
                        temperature=0.2,
                        max_tokens=500,
                    )
                    return self._clean_text(response.choices[0].message.content)
            except Exception as exc:
                errors.append(f"{provider}: {exc}")
        return f"Unable to query configured AI providers: {' | '.join(errors)}"

    def learn_from_sources(self, sources: List[Dict[str, str]]) -> None:
        for source in sources:
            title = source.get("title", "unknown")
            content = source.get("content", "")
            concepts = source.get("concepts", [])
            for concept in concepts:
                self.learn_concept(concept, content, source_title=title)

    def learn_concept(self, concept: str, source_text: str, source_title: str = "source") -> Dict[str, Any]:
        existing = self.local_knowledge["concepts"].get(concept.lower())
        if existing:
            return existing
        
        # Always route through Memory AI if available for ecosystem optimization
        if self.memory_ai and hasattr(self.memory_ai, "receive_contribution"):
            self.memory_ai.receive_contribution(
                agent_id="{DOMAIN_CLASS_NAME.lower()}_agent",
                domain="{DOMAIN_CLASS_NAME.lower()}",
                concept=concept,
                three_ws={
                    "what": source_text[:500],
                    "when": "During spawned-agent learning",
                    "why": f"Learned from {source_title}",
                },
                confidence=0.7,
            )

        record = {
            "source": source_title,
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "confidence": 0.7,
        }
        self.local_knowledge["concepts"][concept.lower()] = record
        self.local_knowledge["sources"].append({"concept": concept, "source": source_title})
        self._save_local_knowledge()
        if self.memory_ai and hasattr(self.memory_ai, "receive_contribution"):
            try:
                self.memory_ai.receive_contribution(
                    agent_id="{DOMAIN_CLASS_NAME.lower()}_agent",
                    domain="{DOMAIN_CLASS_NAME.lower()}",
                    concept=concept,
                    three_ws={
                        "what": source_text[:500],
                        "when": "During spawned-agent learning",
                        "why": f"Learned from {source_title}",
                    },
                    confidence=0.7,
                )
            except Exception:
                pass
        return record

    def answer_query_with_3ws(self, query: str) -> Dict[str, Any]:
        match = self._find_best_concept(query)
        if not match:
            return {
                "query": query,
                "answer": "I could not identify a relevant concept yet.",
                "what": "",
                "when": "",
                "why": "",
            }
        concept, concept_data = match
        return {
            "query": query,
            "concept": concept,
            "what": concept_data.get("what", ""),
            "when": concept_data.get("when", ""),
            "why": concept_data.get("why", ""),
        }

    def _find_best_concept(self, query: str) -> Optional[tuple]:
        candidates = []
        for concept, details in self.local_knowledge.get("concepts", {}).items():
            if concept in query.lower() or any(word in query.lower() for word in concept.split()):
                candidates.append((concept, details))
        return candidates[0] if candidates else None

    def get_knowledge(self) -> Dict[str, Any]:
        if self.memory_ai:
            try:
                return self.memory_ai.get_domain_knowledge("{DOMAIN_CLASS_NAME.lower()}")
            except Exception:
                pass
        return self.local_knowledge

    def get_concept_knowledge(self, concept: str) -> Dict[str, Any]:
        if self.memory_ai:
            try:
                result = self.memory_ai.get_concept("{DOMAIN_CLASS_NAME.lower()}", concept)
                if result:
                    return result
            except Exception:
                pass
        return self.local_knowledge.get("concepts", {}).get(concept.lower(), {})

    def learn_from_other_agents(self) -> List[Dict[str, Any]]:
        if not self.memory_ai:
            return []
        connections = self.memory_ai.get_cross_domain_connections()
        return [c for c in connections if c.get("concept") in self.local_knowledge.get("concepts", {})]

    def _ask_what(self, concept: str, source: str) -> str:
        prompt = f"""
Explain WHAT '{concept}' means for {DOMAIN_CLASS_NAME}.
Use the source material and keep the answer simple and precise.
Source:
{source}
"""
        return self._ask_ai(prompt)

    def _ask_when(self, concept: str, source: str) -> str:
        prompt = f"""
Explain WHEN to use '{concept}' in the context of {DOMAIN_CLASS_NAME}.
Use examples from the source material.
Source:
{source}
"""
        return self._ask_ai(prompt)

    def _ask_why(self, concept: str, source: str) -> str:
        prompt = f"""
Explain WHY '{concept}' works and what mechanism makes it valuable.
Source:
{source}
"""
        return self._ask_ai(prompt)

    def to_dict(self) -> Dict[str, Any]:
        return self.local_knowledge


if __name__ == "__main__":
    kb = {DOMAIN_CLASS_NAME}KnowledgeBase()
    print(json.dumps(kb.get_knowledge(), indent=2))
'''


def render_template(domain_class_name: str) -> str:
    return KNOWLEDGE_BASE_TEMPLATE.replace("{DOMAIN_CLASS_NAME}", domain_class_name)


if __name__ == "__main__":
    from pprint import pprint

    print("This module is a template for spawned agent knowledge bases.")
    pprint({"example": render_template("ExampleDomain")[:200]})
