from __future__ import annotations

from typing import Any, Dict, List


def detect_misinformation(cluster: Dict[str, Any]) -> Dict[str, Any]:
    """
    Deterministic misinformation/propaganda detection stub.

    Produces:
      - misinformation_risk: float 0..1
      - flags: list[str]
      - narrative_signals: list[str]
    """
    items = list(cluster.get("items") or [])
    if not items:
        return {"misinformation_risk": 0.5, "flags": ["empty_cluster"], "narrative_signals": []}

    # Robustly concatenate text fields (some fields may be non-strings)
    parts: List[str] = []
    for it in items:
        title = str(it.get("title") or "")
        summary = str(it.get("summary") or "")
        raw_text = str(it.get("raw_text") or "")
        parts.append(f"{title} {summary} {raw_text}")
    combined_text = " ".join(parts).lower()

    flags: List[str] = []
    narrative_signals: List[str] = []

    def has_any(kws: List[str]) -> bool:
        return any(k in combined_text for k in kws)

    # Sensational / rumor language
    if has_any(["shocking", "breaking", "unbelievable", "secret", "rumor", "allegedly"]):
        flags.append("sensational_or_rumor_language")
        narrative_signals.append("emotionally_loaded_headlines")

    # Lack of sourcing (url empty for many items)
    missing_source_count = sum(
        1 for it in items if not str(it.get("url") or it.get("source") or "").strip()
    )
    if missing_source_count / max(1, len(items)) >= 0.5:
        flags.append("insufficient_citation")
        narrative_signals.append("low_source_transparency")

    # Contradiction proxy: same cluster mentions opposite-direction markers
    bullish = has_any(["up ", "surge", "soaring", "beat estimates", "record high", "strong demand"])
    bearish = has_any(["down ", "plunge", "tumble", "miss estimates", "record low", "weak demand"])
    if bullish and bearish:
        flags.append("contradictory_directional_signals")
        narrative_signals.append("internal_consistency_risk")

    # Propaganda proxy: "we/they" framing & calls to action
    if has_any(["we ", "they ", "our ", "their "]) and has_any(["must ", "only way", "join", "act now", "expose"]):
        flags.append("us_vs_them_prop_like_framing")
        narrative_signals.append("ingroup_outgroup_messaging")

    # AI-generated misinformation proxy: deterministic keyword
    if has_any(["as an ai", "i cannot", "generated by", "this is not real", "deepfake"]):
        flags.append("ai_generated_content_markers")
        narrative_signals.append("synthetic_content_marker")

    # Risk score
    base = 0.25
    base += 0.20 * (1 if "sensational_or_rumor_language" in flags else 0)
    base += 0.25 * (1 if "insufficient_citation" in flags else 0)
    base += 0.15 * (1 if "contradictory_directional_signals" in flags else 0)
    base += 0.15 * (1 if "us_vs_them_prop_like_framing" in flags else 0)

    # Cap
    misinformation_risk = max(0.0, min(1.0, base))
    return {
        "misinformation_risk": float(misinformation_risk),
        "flags": flags,
        "narrative_signals": narrative_signals,
    }
